### ISSUE TITLE
I want to automate my skill for end to end regression testing. Please confirm if I can use this tool and also costing of the tool.

### ISSUE THREAD

**Issue by ChampNBM** [bespoken/virtual-device-example#5]
I want to automate my skill for end to end/ regression testing. Please confirm if I can use this tool.
also Let me know if this is  a free tool?

Also I tried to test my skill by reading documents. I added my virtualDeviceToken. Still I get the response I don't know that. 
Can you please help me on this.

**Comment by jkelvie** [comment]
Hi @ChampNBM -  we will be happy to help you on Gitter - https://gitter.im/bespoken/bst. I see that you posted a question there on Friday, which we replied to. Please do not use tickets for support questions.
